# Generated by Django 4.2.7 on 2023-12-10 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='пользователь')),
                ('name', models.CharField(max_length=100, verbose_name='название привычки')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='место выполнения привычки')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время выполнения привычки')),
                ('action', models.CharField(max_length=100, verbose_name='действие привычки')),
                ('habit_is_good', models.BooleanField(default=True, verbose_name='признак приятной привычки')),
                ('period', models.CharField(choices=[('ежедневно', 'ежедневно'), ('еженедельно', 'еженедельно')], default='ежедневно', max_length=20, verbose_name='периодичность привычки')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='продолжительность выполнения привычки')),
                ('habit_is_public', models.BooleanField(default=True, verbose_name='признак публичной привычки')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название награды')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание награды')),
            ],
            options={
                'verbose_name': 'награда',
                'verbose_name_plural': 'награды',
                'ordering': ('name',),
            },
        ),
    ]
