# Generated by Django 4.2.7 on 2023-12-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_habit_user_alter_habit_habit_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='habit_owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='prize',
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
    ]
