# Generated by Django 4.2.7 on 2023-12-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_rename_habit_owner_habit_user_remove_habit_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='prize',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='вознаграждение'),
        ),
    ]
